### ISSUE TITLE
M2 Turret Issue

### ISSUE THREAD

**Issue by ghost** [KerbalPowers/Refurbished-Armory#1]
I couldn't help but notice the lack of a camera on the left side of the Bradley turret, but other than that, it is a solid model.
![image_2024-11-09_130928150](https://github.com/user-attachments/assets/15157255-ccec-4311-9a5e-cf8a4f9048ad)

**Comment by ghost** [comment]
There also seems to be an issue with the TOW missiles (only one is fired, the other one cannot be) and the rotation of the turrets (they seem to limit themselves to a very small FOV when switching between the two)
Also, there isn't much audio for the gun, don't know if that was intentional.

**Comment by Spartwo** [comment]
Where you'd expect a camera is substituted with BD's FLIR ball, you'll see empty spots on the T90, ELand, and BD's M1 turret too.

**Comment by Spartwo** [comment]
The limited pitch is by design but I do see what you mean by the main gun inheriting the limited range when you swap over

**Comment by ghost** [comment]
Actually, now that I think of it, why not put smoke dischargers on the models, like what was done with the Eland turret?

**Comment by Spartwo** [comment]
The eland having dischargers comes from the original having them. If you're interested in a similar turret with packaged camera and smoke you should check out my other weapons mod full of parts done from scratch.
